#!/bin/bash

##
## Configuration Variables
##

# The name of the keychain to create for iOS code signing.
KEYCHAIN=ios-build.keychain

##
## Delete Certificates
##

delete_certificates ()
{
    # Delete the temporary keychain for code signing.
    security delete-keychain "$KEYCHAIN"
}

##
## Teardown
##

teardown ()
{
    if [ -z "$KEY_PASSWORD" ]
    then
        return 0
    fi

    delete_certificates
}

teardown
